---
- name: Install ipa-client on centos
  yum:
    name: freeipa-client
    update_cache: yes
    state: present

- name: Check if host is enrolled
  register: freeipaclient_ipaconf
  check_mode: no
  stat:
    path: /etc/ipa/default.conf

- name: Enroll host
  when: not freeipaclient_ipaconf.stat.exists
  command: >
    ipa-client-install
    --principal={{ freeipa_enroll_user }}
    --password={{ freeipa_enroll_passwd }}
    --mkhomedir
    --enable-dns-updates
    --force-ntpd
    --unattended
    --force-join

- name: Disable selinux in sssd
  ini_file:
    path: /etc/sssd/sssd.conf
    section: "domain/{{ freeipa_enroll_domain }}"
    option: selinux_provider
    value: none
    mode: 0600
    backup: no

- name: Restart sssd
  service:
    name: sssd
    state: restarted
